# Generated by Django 6.0.2 on 2026-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_projectgoal_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
            ],
        ),
        migrations.AddField(
            model_name='projectgoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='projectgoal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goals', to='pages.tag', verbose_name='Теги'),
        ),
    ]
